name: CI UWP

on: [push]
env:
  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild Path
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1.2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.2

    - name: Run Test
      run: dotnet test --logger:"junit;LogFilePath=dotnet-test-result.xml"
    
    
    - name: Publish Test Report
        uses: mikepenz/action-junit-report@v3
        if: always() # always run even if the previous step fails
        with:
          report_paths: 'dotnet-test-result.xml'

