name: CI UWP

on: [push]
#env:
#  ACTIONS_ALLOW_UNSECURE_COMMANDS: true
jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup MSBuild Path
      uses: microsoft/setup-msbuild@v1.1

    - name: Setup VSTest Path
      uses: darenm/Setup-VSTest@v1.2

    #- name: Setup NuGet
    #  uses: NuGet/setup-nuget@v1.0.2

    - name: Run Test
      run: dotnet test --logger:"trx;LogFilePath=TestResults/dotnet-test-result.trx"
    - name: Publish Test Results
      uses: EnricoMi/publish-unit-test-result-action/composite@v2
      if: always()
      with:
        trx_files: "HerokuTest1/TestResults/*.trx"